// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjlkj5pLkRZLdmIpLpi-frggWOoeShaks',
    appId: '1:152850594441:web:d0a2184d4a465184272458',
    messagingSenderId: '152850594441',
    projectId: 'hootv-50a06',
    authDomain: 'hootv-50a06.firebaseapp.com',
    storageBucket: 'hootv-50a06.appspot.com',
    measurementId: 'G-E5P5V32JVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD0yI1As9Z_3pNWVYSR43_mWKVGqgjl38',
    appId: '1:152850594441:android:51deb9b559badcd1272458',
    messagingSenderId: '152850594441',
    projectId: 'hootv-50a06',
    storageBucket: 'hootv-50a06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFN7bk-GIQSDk0dDq7GnFJlaNLDbUAcRs',
    appId: '1:152850594441:ios:f11b3e0b5c3bba59272458',
    messagingSenderId: '152850594441',
    projectId: 'hootv-50a06',
    storageBucket: 'hootv-50a06.appspot.com',
    iosBundleId: 'com.hoo.app.hootv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFN7bk-GIQSDk0dDq7GnFJlaNLDbUAcRs',
    appId: '1:152850594441:ios:1325127b09cb47ff272458',
    messagingSenderId: '152850594441',
    projectId: 'hootv-50a06',
    storageBucket: 'hootv-50a06.appspot.com',
    iosBundleId: 'com.hoo.app.hootv.RunnerTests',
  );
}
